name: jaguar_ipnet
description: An extensive library to handle IP addresses
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
